// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFGcjUnHIruqFoQr5dB1Hm3YLbM5tEsg',
    appId: '1:854105300043:android:cd63ab0f6fe258fd68c1ce',
    messagingSenderId: '854105300043',
    projectId: 'nove-p3-10',
    storageBucket: 'nove-p3-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPSITfiGw6tuCqx-LiXaxoLJwuV532lY',
    appId: '1:854105300043:ios:dc9683e2e977ef1f68c1ce',
    messagingSenderId: '854105300043',
    projectId: 'nove-p3-10',
    storageBucket: 'nove-p3-10.firebasestorage.app',
    iosBundleId: 'com.example.noveP5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPSITfiGw6tuCqx-LiXaxoLJwuV532lY',
    appId: '1:854105300043:ios:dc9683e2e977ef1f68c1ce',
    messagingSenderId: '854105300043',
    projectId: 'nove-p3-10',
    storageBucket: 'nove-p3-10.firebasestorage.app',
    iosBundleId: 'com.example.noveP5',
  );
}
